### ISSUE TITLE
Unbundled qUINT shaders cause duplicate listings. 

### ISSUE THREAD

**Issue by whaleologist** [ipsusu/IpsuShade#3]
Hello! 

I've been loving IpsuShade since the GShade era, happily on ReShade now. 
One thing I have noticed is that a standard ReShade install pre-bundles the qUINT package under /reshade-shaders/Shaders/qUINT, however installing IpsuShade adds a second copy of each qUINT .fx to the /reshade-shaders/Shaders/ directory, causing a duplication in the ReShade UI. 

Is it possible to bundle the qUINT shaders included in the IpsuShade install .zip to a folder similar to how ReShade does, or would this break more things than it fixes? Nonetheless, very small issue, happily remedied it myself, but thought it might be worth bringing to your attention nonetheless.

Thanks for a fantastic set of presets!

**Comment by ipsusu** [comment]
Hi!

Many apologies for the delayed reply, I remember getting this notification but then I never followed up on it. Thanks for using my stuff for so long! 

Yes, this is a discrepancy between how GShade organised (or, lack thereof) the shaders versus vanilla ReShade. 

I wrote a long explanation about my reasoning for sticking with the GShade style of organisation versus ReShade here: https://github.com/ipsusu/IpsuShade/issues/1#issuecomment-1426973201

I can't actually redistribute any modern versions of the qUINT shaders due to a change in license, but I'm planning on making a version of IpsuShade that uses the ReShade installer to download qUINT, and will have properly organised ReShade folders for any of my custom stuff. 

I haven't done this yet, as its kind of low priority since it's easily fixed by a knowledgeable user, but when I do a bigger release somewhere down the line, I'll be sure to include this compatible version as an option.

Thanks for your message and I appreciate your support!

**Comment by ipsusu** [comment]
Finally, implemented in [ipsuShade v2.0.0](https://github.com/ipsusu/ipsuShade/releases/tag/v2.0.0). Apologies for the delay!
